
title: Tiwari-Talks

author: Anish Tiwari



navbar-links:
  About Me: "aboutme"
  Links:
    - Instagram: "https://www.instagram.com/venomish05/"


avatar: "/assets/img/avatar-icon.png"

round-avatar: true



rss-description: This website is a made for Anish Tiwari.


share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false


url-pretty: "https://www.instagram.com/venomish05/"


excerpt_length: 50

feed_show_excerpt: true

feed_show_tags: true


navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

date_format: "%B %-d, %Y"


timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  
      social-share: true
  -
    scope:
      path: "" 
    values:
      layout: "page"


exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap



